### ISSUE TITLE
Reverse token

### ISSUE THREAD

**Issue by kajetan-nobel** [mblarsen/shortcode-tokenizer#6]
Hi, what do you thinking about implement reverse tokenizer - from object to string with all params.

PS. You did really good job with this package.

**Comment by mblarsen** [comment]
I'm doing a little bit of that in https://github.com/mblarsen/shortcode-editor - maybe you can get some inspiration from that.

Try to search for `buildTemplate` in that repo. It would be cool to have proper functionality for it.

> NOTE: This example was developed for a concrete backend so some of the logic may seem really odd and even break.
